spring:
  profiles:
    active: dev
  redis:
    url: ${REDIS_URL}
  mail:
    host: ${JAVA_MAIL}
    port: ${JAVA_MAIL_PORT}
    username: ${JAVA_MAIL_USERNAME}
    password: ${JAVA_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: ${WEATHER_API_KEY}